function cl=fibercrops
% ROOTTUBERCROPS - get the names of the pulse crops
%
% SYNTAX
% c=roottubercrops - set c to a cell array of the roottuber crops

cl={'cotton',...
'flax',...
'hemp',...
'jute',...
'jutelikefiber',...
'ramie',...
'sisal',...
'agave',...
'abaca',...
'fibrenes',...
'kapokfiber',...
'kapokseed',...
'coir'};
