function cl=foragecrops
% ROOTTUBERCROPS - get the names of the pulse crops
%
% SYNTAX
% c=roottubercrops - set c to a cell array of the roottuber crops

cl={'maizefor',...
'sorghumfor',...
'ryefor',...
'grassnes',...
'clover',...
'alfalfa',...
'oilseedfor',...
'legumenes',...
'cabbagefor',...
'mixedgrass',...
'turnipfor',...
'beetfor',...
'carrotfor',...
'swedefor',...
'fornes',...
'vegfor'};
