function cl=fruitcrops
% FRUITCROPS - get the names of the sixteen main crops
%
% SYNTAX
% c=fruitcrops - set c to a cell array of the fruit crops

cl={'quince',...
'apricot',...
'sourcherry',...
'cherry',...
'peachetc',...
'plum',...
'stonefruitnes',...
'strawberry',...
'rasberry',...
'gooseberry',...
'currant',...
'blueberry',...
'cranberry',...
'berrynes',...
'grape',...
'fig',...
'mango',...
'avocado',...
'pineapple',...
'date',...
'persimmon',...
'cashewapple',...
'kiwi',...
'papaya',...
'tropicalnes',...
'carob',...
'banana',...
'plantain',...
'orange',...
'tangetc',...
'lemonlime',...
'grapefruitetc',...
'citrusnes',...
'apple',...
'pear',...
'fruitnes'};
