function cl=highpollinatorcrops
% FRUITCROPS - get the names of the oil crops
%
% SYNTAX
% c=oilcrops - set c to a cell array of the oil crops

cl={'brazil',...
'melonetc',...
'cocoa',...
'kiwi',...
'melonseed',...
'pumpkinetc',...
'quince',...
'vanilla',...
'watermelon',...
'almond',...
'aniseetc',...
'apple',...
'apricot',...
'avocado',...
'berrynes',...
'blueberry',...
'buckwheat',...
'carrot',...
'cashew',...
'cherry',...
'cranberry',...
'cucumberetc',...
'mango',...
'nutmeg',...
'peachetc',...
'pear',...
'plum',...
'rasberry',...
'sourcherry'...

};

