function cl=lowpollinatorcrops
% FRUITCROPS - get the names of the oil crops
%
% SYNTAX
% c=oilcrops - set c to a cell array of the oil crops

cl={'tropicalnes',...
'fruitnes',...
'coffee',...
'greenbroadbean',...
'chestnut',...
'coconut',...
'currant',...
'eggplant',...
'fig',...
'lupin',...
'mustard',...
'okra',...
'rapeseed',...
'sesame',...
'karite',...
'soybean',...
'strawberry',...
'sunflower',...
'nutnes',...
'bean',...
'broadbean',...
'chilleetc',...
'cowpea',...
'grapefruitetc',...
'groundnut',...
'lemonlime',...
'oilpalm',...
'orange',...
'papaya',...
'persimmon',...
'pigeonpea',...
'pulsenes',...
'safflower',...
'stringbean',...
'tangetc',...
'tomato'...

};

