function cl=cerealcrops
% ROOTTUBERCROPS - get the names of the pulse crops
%
% SYNTAX
% c=roottubercrops - set c to a cell array of the roottuber crops

cl={'wheat',...
'rice',...
'barley',...
'maize',...
'popcorn',...
'rye',...
'oats',...
'millet',...
'sorghum',...
'buckwheat',...
'quinoa',...
'fonio',...
'triticale',...
'canaryseed',...
'mixedgrain',...
'cerealnes'};
