function cl=oilcrops
% FRUITCROPS - get the names of the oil crops
%
% SYNTAX
% c=oilcrops - set c to a cell array of the oil crops

cl={'soybean',...
'groundnut',...
'coconut',...
'oilpalm',...
'olive',...
'karite',...
'castor',...
'sunflower',...
'rapeseed',...
'tung',...
'safflower',...
'sesame',...
'mustard',...
'poppy',...
'melonseed',...
'linseed',...
'hempseed',...
'oilseednes'};
