function cl=othercrops
% FRUITCROPS - get the names of the oil crops
%
% SYNTAX
% c=oilcrops - set c to a cell array of the oil crops

cl={'chicory',...
'hop',...
'peppermint',...
'pyrethrum',...
'areca',...
'kolanut',...
'pepper',...
'pimento',...
'vanilla',...
'cinnamon',...
'nutmeg',...
'clove',...
'aniseetc',...
'ginger',...
'spicenes',...
'tobacco',...
'tea',...
'coffee',...
'cocoa',...
'mate',...
'rubber',...
'gums'};
