function cl=pulsecrops
% PULSECROPS - get the names of the pulse crops
%
% SYNTAX
% c=pulsecrops - set c to a cell array of the pulse crops

cl={'bean',...
'broadbean',...
'pea',...
'chickpea',...
'cowpea',...
'pigeonpea',...
'lentil',...
'bambara',...
'vetch',...
'pulsenes',...
'lupin'};
