function cl=roottubercrops
% ROOTTUBERCROPS - get the names of the pulse crops
%
% SYNTAX
% c=roottubercrops - set c to a cell array of the roottuber crops

cl={'potato',...
'sweetpotato',...
'cassava',...
'yautia',...
'taro',...
'yam',...
'rootnes'};
