function cl=shrubcrops
% FRUITCROPS - get the names of the oil crops
%
% SYNTAX
% c=oilcrops - set c to a cell array of the oil crops

cl={'ramie',...
'sisal',...
'agave',...
'abaca',...
'strawberry',...
'rasberry',...
'gooseberry',...
'blueberry',...
'cranberry',...
'berrynes',...
'grape',...
'pineapple',...
'banana',...
'plantain',...
'hop',...
'pyrethrum',...
'pepper',...
'vanilla',...
'nutmeg',...
'tea',...
'coffee',...
'cocoa',...
'mate'};

