function cl=treenutcrops
% ROOTTUBERCROPS - get the names of the pulse crops
%
% SYNTAX
% c=roottubercrops - set c to a cell array of the roottuber crops

cl={'brazil',...
'cashew',...
'chestnut',...
'almond',...
'walnut',...
'pistachio',...
'hazelnut',...
'nutnes'};
