function cl=treecrops
% FRUITCROPS - get the names of the oil crops
%
% SYNTAX
% c=oilcrops - set c to a cell array of the oil crops

cl={'kapokfiber',...
'kapokseed',...
'coir',...
'quince',...
'apricot',...
'sourcherry',...
'cherry',...
'peachetc',...
'plum',...
'stonefruitnes',...
'currant',...
'fig',...
'mango',...
'avocado',...
'date',...
'persimmon',...
'cashewapple',...
'kiwi',...
'papaya',...
'tropicalnes',...
'fruitnes',...
'carob',...
'orange',...
'tangetc',...
'lemonlime',...
'grapefruitetc',...
'citrusnes',...
'apple',...
'pear',...
'coconut',...
'oilpalm',...
'olive',...
'karite',...
'tung',...
'areca',...
'kolanut',...
'cinnamon',...
'clove',...
'spicenes',...
'rubber',...
'gums',...
'brazil',...
'cashew',...
'chestnut',...
'almond',...
'walnut',...
'pistachio',...
'hazelnut',...
'nutnes'
};

