function cl=vegmeloncrops
% ROOTTUBERCROPS - get the names of the pulse crops
%
% SYNTAX
% c=roottubercrops - set c to a cell array of the roottuber crops

cl={'cabbage',...
'artichoke',...
'asparagus',...
'lettuce',...
'spinach',...
'tomato',...
'cauliflower',...
'pumpkinetc',...
'cucumberetc',...
'eggplant',...
'chilleetc',...
'greenonion',...
'onion',...
'garlic',...
'greenbean',...
'greenpea',...
'greenbroadbean',...
'stringbean',...
'carrot',...
'okra',...
'greencorn',...
'mushroom',...
'vegetablenes',...
'watermelon',...
'melonetc'};
