function cl=tencrops
% TENCROPS - get the names of the sixteen main crops
%
% SYNTAX
% c=tencrops - set c to a cell array of the sixteen main crops

cl={'barley',...
'cassava',...
'maize',...
'oilpalm',...
'rapeseed',...
'rice',...
'sorghum',...
'soybean',...
'sugarcane',...
'wheat'};
