function layeredkml(image,name)
% LAYEREDKML - create a kmz using a pyramid data structure
%
%  Syntax
%
%    finemap(colormap,lowercolor,uppercolor);

mkdir(name);
mkdir(name,'file');
fid=fopen([name '/doc.kml'],'w');
fprintf(fid,['<?xml version="1.0" encoding="UTF-8"?>'...
'<kml xmlns="http://www.opengis.net/kml/2.2">'...
  '<NetworkLink>'...
    '<name>SuperOverlay: ' name '</name>'...
    '<Region>'...
      '<LatLonAltBox>'...
        '<north>90</north>'...
        '<south>-90</south>'...
        '<east>180</east>'...
        '<west>-180</west>'...
      '</LatLonAltBox>'...
      '<Lod>'...
        '<minLodPixels>200</minLodPixels>'...
        '<maxLodPixels>-1</maxLodPixels>'...
      '</Lod>'...
    '</Region>'...
    '<Link>'...
      '<href>111.kml</href>'...
      '<viewRefreshMode>onRegion</viewRefreshMode>'...
    '</Link>'...
  '</NetworkLink>'...
'</kml>']);
for level=1:4
    for hori=1:2^(level-1)
        for vert=1:2^(level-1)
            imwrite(imresize(image((vert-1)*2160/(2^(level-1))+1:vert*2160/(2^(level-1)),(hori-1)*4320/(2^(level-1))+1:hori*4320/(2^(level-1)),:),[270,540]),[name '/file/' num2str(level*100+vert*10+hori) '.png']);
                fid=fopen([name '/' num2str(level*100+hori*10+vert) '.kml'],'w');
    fprintf(fid,['<?xml version="1.0" encoding="UTF-8"?>'...
'<kml xmlns="http://www.opengis.net/kml/2.2">'...
  '<Document>'...
    '<Region>'...
      '<Lod>'...
        '<minLodPixels>200</minLodPixels><maxLodPixels>-1</maxLodPixels>'...
      '</Lod>'...
      '<LatLonAltBox>'...
        '<north>' num2str(90-((vert-1)*(180/(2^(level-1))))) '</north><south>' num2str(90-(vert*(180/(2^(level-1))))) '</south>'...
        '<east>' num2str(180-((hori-1)*(360/(2^(level-1))))) '</east><west>' num2str(180-(hori*(360/(2^(level-1))))) '</west>'...
      '</LatLonAltBox>'...
    '</Region>'...
    '<NetworkLink>'...
      '<name>' num2str((level+1)*100+((vert*2)-1)*10+(hori*2)-1) '</name>'...
      '<Region>'...
        '<Lod>'...
          '<minLodPixels>200</minLodPixels><maxLodPixels>-1</maxLodPixels>'...
        '</Lod>'...
        '<LatLonAltBox>'...
          '<north>' num2str(90-(((vert*2)-2)*(180/((2^(level)))))) '</north><south>' num2str(90-(((vert*2)-1)*(180/((2^(level)))))) '</south>'...
          '<east>' num2str(180-(((hori*2)-2)*(360/((2^(level)))))) '</east><west>' num2str(180-(((hori*2)-1)*(360/((2^(level)))))) '</west>'...
        '</LatLonAltBox>'...
      '</Region>'...
      '<Link>'...
        '<href>' num2str((level+1)*100+((vert*2)-1)*10+(hori*2)-1) '.kml</href>'...
        '<viewRefreshMode>onRegion</viewRefreshMode>'...
      '</Link>'...
    '</NetworkLink>'...
    '<NetworkLink>'...
      '<name>' num2str((level+1)*100+(vert*2)*10+(hori*2)-1) '</name>'...
      '<Region>'...
        '<Lod>'...
          '<minLodPixels>200</minLodPixels><maxLodPixels>-1</maxLodPixels>'...
        '</Lod>'...
        '<LatLonAltBox>'...
          '<north>' num2str(90-(((vert*2)-1)*(180/((2^(level)))))) '</north><south>' num2str(90-((vert*2)*(180/((2^(level)))))) '</south>'...
          '<east>' num2str(180-(((hori*2)-2)*(360/((2^(level)))))) '</east><west>' num2str(180-(((hori*2)-1)*(360/((2^(level)))))) '</west>'...
        '</LatLonAltBox>'...
      '</Region>'...
      '<Link>'...
        '<href>' num2str((level+1)*100+(vert*2)*10+(hori*2)-1) '.kml</href>'...
        '<viewRefreshMode>onRegion</viewRefreshMode>'...
      '</Link>'...
    '</NetworkLink>'...
    '<NetworkLink>'...
      '<name>' num2str((level+1)*100+((vert*2)-1)*10+(hori*2)) '</name>'...
      '<Region>'...
        '<Lod>'...
          '<minLodPixels>200</minLodPixels><maxLodPixels>-1</maxLodPixels>'...
        '</Lod>'...
        '<LatLonAltBox>'...
          '<north>' num2str(90-(((vert*2)-2)*(180/((2^(level)))))) '</north><south>' num2str(90-(((vert*2)-1)*(180/((2^(level)))))) '</south>'...
          '<east>' num2str(180-(((hori*2)-1)*(360/((2^(level)))))) '</east><west>' num2str(180-((hori*2)*(360/((2^(level)))))) '</west>'...
        '</LatLonAltBox>'...
      '</Region>'...
      '<Link>'...
        '<href>' num2str((level+1)*100+((vert*2)-1)*10+(hori*2)) '.kml</href>'...
        '<viewRefreshMode>onRegion</viewRefreshMode>'...
      '</Link>'...
    '</NetworkLink>'...
    '<NetworkLink>'...
      '<name>' num2str((level+1)*100+(vert*2)*10+(hori*2)) '</name>'...
      '<Region>'...
        '<Lod>'...
          '<minLodPixels>200</minLodPixels><maxLodPixels>-1</maxLodPixels>'...
        '</Lod>'...
        '<LatLonAltBox>'...
          '<north>' num2str(90-(((vert*2)-1)*(180/((2^(level)))))) '</north><south>' num2str(90-((vert*2)*(180/((2^(level)))))) '</south>'...
          '<east>' num2str(180-(((hori*2)-1)*(360/((2^(level)))))) '</east><west>' num2str(180-((hori*2)*(360/((2^(level)))))) '</west>'...
        '</LatLonAltBox>'...
      '</Region>'...
      '<Link>'...
        '<href>' num2str((level+1)*100+(vert*2)*10+(hori*2)) '.kml</href>'...
        '<viewRefreshMode>onRegion</viewRefreshMode>'...
      '</Link>'...
    '</NetworkLink>'...
    '<GroundOverlay>'...
      '<drawOrder>' num2str(level) '</drawOrder>'...
      '<Icon>'...
        '<href>file/' num2str(level*100+vert*10+2^(level-1)+1-hori) '.png</href>'...
      '</Icon>'...
      '<LatLonBox>'...
        '<north>' num2str(90-((vert-1)*(180/(2^(level-1))))) '</north><south>' num2str(90-(vert*(180/(2^(level-1))))) '</south>'...
        '<east>' num2str(180-((hori-1)*(360/(2^(level-1))))) '</east><west>' num2str(180-(hori*(360/(2^(level-1))))) '</west>'...
      '</LatLonBox>'...
    '</GroundOverlay>'...
  '</Document>'...
'</kml>']);
        end
    end
end


     zip([name '_kml.zip'],...
         {'*.kml','file/*.png'},...
         name);
     movefile([name '_kml.zip'],...
         [name '.kmz']);