function layeredkmllegend(data,name,cmap,folder,shortname,cmin,cmax)
% LAYEREDKMLLEGEND - create a kmz using a pyramid data structure
%
%  Syntax
%
%  layeredkmllegend(data,name) will create a legend for the given
%  data 'data' and use 'name' as a directory as well as title
%
%  layeredkmllegend(data,name,cmap,folder,shortname,cmin,cmax) lets the
%  user additionally specify a colormap, directory, short version of the
%  title, and colorbar min and max

if (nargin<3)
    cmap='jet';
end
if (nargin<5)
    shortname=name;
end
if (nargin<4)
    folder=shortname;
end
if (nargin<6)
    cmin=percentile(data,.01);
end
if (nargin<7)
    cmax=percentile(data,100);
end
mkdir(name);
mkdir(name,'file');
size(data)
MakeGlobalOverlay(data,'brightyield',[.98],'1234567890.png',0.3);
image=imread('1234567890.png');
eval(['makeLegendGeneral(' cmap ',[name ''/file''],name,cmin,cmax)']);
fid=fopen([name '/doc.kml'],'w');
fprintf(fid,['<?xml version="1.0" encoding="UTF-8"?>'...
'<kml xmlns="http://www.opengis.net/kml/2.2">'...
  '<NetworkLink>'...
    '<name>SuperOverlay: ' name '</name>'...
    '<Region>'...
      '<LatLonAltBox>'...
        '<north>90</north>'...
        '<south>-90</south>'...
        '<east>180</east>'...
        '<west>-180</west>'...
      '</LatLonAltBox>'...
      '<Lod>'...
        '<minLodPixels>200</minLodPixels>'...
        '<maxLodPixels>-1</maxLodPixels>'...
      '</Lod>'...
    '</Region>'...
    '<Link>'...
      '<href>111.kml</href>'...
      '<viewRefreshMode>onRegion</viewRefreshMode>'...
    '</Link>'...
  '</NetworkLink>'...
'</kml>']);
        %'<Icon>\n'...
        %'<href>file/logo.png</href>\n'...
        %'</Icon>\n'...
for level=1:4
    for hori=1:2^(level-1)
        for vert=1:2^(level-1)
            imwrite(imresize(image((vert-1)*2160/(2^(level-1))+1:vert*2160/(2^(level-1)),(hori-1)*4320/(2^(level-1))+1:hori*4320/(2^(level-1)),:),[270,540]),[name '/file/' num2str(level*100+vert*10+hori) '.png']);
                fid=fopen([name '/' num2str(level*100+hori*10+vert) '.kml'],'w');
    fprintf(fid,['<?xml version="1.0" encoding="UTF-8"?>'...
'<kml xmlns="http://www.opengis.net/kml/2.2">'...
  '<Document>'...
    '<Region>'...
      '<Lod>'...
        '<minLodPixels>200</minLodPixels><maxLodPixels>-1</maxLodPixels>'...
      '</Lod>'...
      '<LatLonAltBox>'...
        '<north>' num2str(90-((vert-1)*(180/(2^(level-1))))) '</north><south>' num2str(90-(vert*(180/(2^(level-1))))) '</south>'...
        '<east>' num2str(180-((hori-1)*(360/(2^(level-1))))) '</east><west>' num2str(180-(hori*(360/(2^(level-1))))) '</west>'...
      '</LatLonAltBox>'...
    '</Region>'...
    '<NetworkLink>'...
      '<name>' num2str((level+1)*100+((vert*2)-1)*10+(hori*2)-1) '</name>'...
      '<Region>'...
        '<Lod>'...
          '<minLodPixels>200</minLodPixels><maxLodPixels>-1</maxLodPixels>'...
        '</Lod>'...
        '<LatLonAltBox>'...
          '<north>' num2str(90-(((vert*2)-2)*(180/((2^(level)))))) '</north><south>' num2str(90-(((vert*2)-1)*(180/((2^(level)))))) '</south>'...
          '<east>' num2str(180-(((hori*2)-2)*(360/((2^(level)))))) '</east><west>' num2str(180-(((hori*2)-1)*(360/((2^(level)))))) '</west>'...
        '</LatLonAltBox>'...
      '</Region>'...
      '<Link>'...
        '<href>' num2str((level+1)*100+((vert*2)-1)*10+(hori*2)-1) '.kml</href>'...
        '<viewRefreshMode>onRegion</viewRefreshMode>'...
      '</Link>'...
    '</NetworkLink>'...
    '<NetworkLink>'...
      '<name>' num2str((level+1)*100+(vert*2)*10+(hori*2)-1) '</name>'...
      '<Region>'...
        '<Lod>'...
          '<minLodPixels>200</minLodPixels><maxLodPixels>-1</maxLodPixels>'...
        '</Lod>'...
        '<LatLonAltBox>'...
          '<north>' num2str(90-(((vert*2)-1)*(180/((2^(level)))))) '</north><south>' num2str(90-((vert*2)*(180/((2^(level)))))) '</south>'...
          '<east>' num2str(180-(((hori*2)-2)*(360/((2^(level)))))) '</east><west>' num2str(180-(((hori*2)-1)*(360/((2^(level)))))) '</west>'...
        '</LatLonAltBox>'...
      '</Region>'...
      '<Link>'...
        '<href>' num2str((level+1)*100+(vert*2)*10+(hori*2)-1) '.kml</href>'...
        '<viewRefreshMode>onRegion</viewRefreshMode>'...
      '</Link>'...
    '</NetworkLink>'...
    '<NetworkLink>'...
      '<name>' num2str((level+1)*100+((vert*2)-1)*10+(hori*2)) '</name>'...
      '<Region>'...
        '<Lod>'...
          '<minLodPixels>200</minLodPixels><maxLodPixels>-1</maxLodPixels>'...
        '</Lod>'...
        '<LatLonAltBox>'...
          '<north>' num2str(90-(((vert*2)-2)*(180/((2^(level)))))) '</north><south>' num2str(90-(((vert*2)-1)*(180/((2^(level)))))) '</south>'...
          '<east>' num2str(180-(((hori*2)-1)*(360/((2^(level)))))) '</east><west>' num2str(180-((hori*2)*(360/((2^(level)))))) '</west>'...
        '</LatLonAltBox>'...
      '</Region>'...
      '<Link>'...
        '<href>' num2str((level+1)*100+((vert*2)-1)*10+(hori*2)) '.kml</href>'...
        '<viewRefreshMode>onRegion</viewRefreshMode>'...
      '</Link>'...
    '</NetworkLink>'...
    '<NetworkLink>'...
      '<name>' num2str((level+1)*100+(vert*2)*10+(hori*2)) '</name>'...
      '<Region>'...
        '<Lod>'...
          '<minLodPixels>200</minLodPixels><maxLodPixels>-1</maxLodPixels>'...
        '</Lod>'...
        '<LatLonAltBox>'...
          '<north>' num2str(90-(((vert*2)-1)*(180/((2^(level)))))) '</north><south>' num2str(90-((vert*2)*(180/((2^(level)))))) '</south>'...
          '<east>' num2str(180-(((hori*2)-1)*(360/((2^(level)))))) '</east><west>' num2str(180-((hori*2)*(360/((2^(level)))))) '</west>'...
        '</LatLonAltBox>'...
      '</Region>'...
      '<Link>'...
        '<href>' num2str((level+1)*100+(vert*2)*10+(hori*2)) '.kml</href>'...
        '<viewRefreshMode>onRegion</viewRefreshMode>'...
      '</Link>'...
    '</NetworkLink>'...
    '<GroundOverlay>'...
      '<drawOrder>' num2str(level) '</drawOrder>'...
      '<Icon>'...
        '<href>file/' num2str(level*100+vert*10+2^(level-1)+1-hori) '.png</href>'...
      '</Icon>'...
      '<LatLonBox>'...
        '<north>' num2str(90-((vert-1)*(180/(2^(level-1))))) '</north><south>' num2str(90-(vert*(180/(2^(level-1))))) '</south>'...
        '<east>' num2str(180-((hori-1)*(360/(2^(level-1))))) '</east><west>' num2str(180-(hori*(360/(2^(level-1))))) '</west>'...
      '</LatLonBox>'...
    '</GroundOverlay>'...
              '<ScreenOverlay>\n'...
        '<name>Legend</name>\n'...
        '<Icon>\n'...
        '<href>file/legend.png</href>\n'...
        '</Icon>\n'...
        '<overlayXY x="0" y="1" xunits="fraction" yunits="fraction"/>\n'...
        '<screenXY x="0" y="1" xunits="fraction" yunits="fraction"/>\n'...
        '<rotationXY x="0" y="0" xunits="fraction" yunits="fraction"/>\n'...
        '<size x="180" y="66" xunits="pixels" yunits="pixels"/>\n'...
        '</ScreenOverlay>\n'...
        '<ScreenOverlay>\n'...
        '<name>GLI</name>\n'...
        '<overlayXY x="0" y="0" xunits="fraction" yunits="fraction"/>\n'...
        '<screenXY x="0" y="0" xunits="fraction" yunits="fraction"/>\n'...
        '<rotationXY x="0" y="0" xunits="fraction" yunits="fraction"/>\n'...
        '<size x="0" y="0" xunits="fraction" yunits="fraction"/>\n'...
        '</ScreenOverlay>\n'...
  '</Document>'...
'</kml>']);
        end
    end
end
    
   % zip outfiles/area/[crop]_overlay and call the resulting file
   % [crop]_area.kmz
     zip([name '_kml.zip'],...
         {'*.kml','file/*.png'},...
         name);
     movefile([name '_kml.zip'],...
         [folder shortname '.kmz']);
rmdir(name,'s');