function makekml(KS)
%MAKEKML - make a kml file for overlay
%
%  this file prints out a .kml
%
%  file is named 
%  Syntax makekml(KS)
%
%   KS fields
%
%KS.folderbase='./kmlfolder'
%KS.header1='header 1'
%KS.description1='desc 1'
%KS.header2='header 2'
%KS.description2='desc 2'
%KS.overlayname='overlay.png';
%KS.logoname='';
%KS.legendname='';
%
%
%  See Also makekmzfile makelegend
folderbase='./kmlfolder';
header1='header 1'
description1='desc 1'
header2=''
description2=''
overlayname='overlay.png';
logoname='';
legendname='';


expandstructure(KS)



fid=fopen([ folderbase '/doc.kml'],'w');

fprintf(fid,['<?xml version="1.0" encoding="UTF-8"?>\n'...
    '<kml xmlns="http://www.opengis.net/kml/2.2">\n'...
    '<Folder>\n'... % these \n newline indicators are not necessary but make it look nicer
    '<name>' header1 '</name>\n' ...
    '<description>' description1 '</description>\n'...
    '<GroundOverlay>\n']);

if ~isempty(header2)
    fprintf(fid,[ '<name>' header2 '</name>\n']);
end

if ~isempty(description2)
    fprintf(fid,[ '<description>' description2 '</description>\n'])
end

    fprintf(fid,['<Icon>\n'...
    '<href>' folderbase '/overlay.png</href>\n']);
    fprintf(fid,...
    ['</Icon>\n'...
    '<LatLonBox>\n'...
    '<north>90.0</north>\n'...
    '<south>-90.0</south>\n'...
    '<east>-180.0</east>\n'...
    '<west>180.0</west>\n'...
    '</LatLonBox>\n'...
    '</GroundOverlay>\n']...
    );


% if legend
if ~isempty(legendname)
    
    copyfile(legendname,[folderbase '/legend.png']);

fprintf(fid,['<ScreenOverlay> \n',...
    '<name>Legend</name>\n',...
    '<Icon>\n',...
    '<href>' folderbase '/legend.png</href>\n',...
    '</Icon>\n',...
    '<overlayXY x="0" y="1" xunits="fraction" yunits="fraction"/>\n',...
    '<screenXY x="0" y="1" xunits="fraction" yunits="fraction"/>\n',...
    '<rotationXY x="0" y="0" xunits="fraction" yunits="fraction"/>\n',...
    '<size x="180" y="66" xunits="pixels" yunits="pixels"/>\n',...
    '</ScreenOverlay>\n']);
end

if ~isempty(logoname)

    copyfile(logoname,[folderbase '/logo.png']);

    
fprintf(fid,[ '<ScreenOverlay> \n',...
    '<name>GLI</name>\n',...
    '<Icon>\n',...
    '<href>' folderbase '/logo.png</href>\n',...
    '</Icon>\n',...
    '<overlayXY x="0" y="0" xunits="fraction" yunits="fraction"/>\n',...
    '<screenXY x="0" y="0" xunits="fraction" yunits="fraction"/>\n',...
    '<rotationXY x="0" y="0" xunits="fraction" yunits="fraction"/>\n',...
    '<size x="0" y="0" xunits="fraction" yunits="fraction"/>\n',...
    '</ScreenOverlay>\n']);

end

fprintf(fid,['</Folder>\n'...
    '</kml>\n']);

fclose(fid);

    
    
   