load list
tmp=opennetcdf([list{1} '_5min.nc']);
Long1=zeros(4320,2160);
for i=1:4320
    Long1(i,1:2160)=tmp.Long(i,1);
end
Long1=rot90(Long1);
Lat1=zeros(4320,2160);
for i=1:2160
    Lat1(1:4320,i)=tmp.Lat(i,1);
end
Lat1=rot90(Lat1);
for i=1:length(list)
    i=i+(i==128);
    waitbar(i/length(list),['Processing ' list{i}]);
    tmp=opennetcdf([iddstring 'Crops2000/Crops/' list{i} '_5min.nc']);
    area=tmp.Data(:,:,1)*100;
    yield=tmp.Data(:,:,2);
    tmps=strrep(strrep(strrep(list{i},'nes', ' (other)'),'for',' (for silage)'),'etc',', etc.');
%     T.area=area;
%     T.yield=yield;
%     copyfile([list{1} '_5min.nc'],['outfiles/area/' list{i} '_data.nc']);
%     AMTSurf(area,['Percentage of land dedicated to ' tmps ' cultivation'],...
%         ['outfiles/area/' list{i} '_area.png']);
%     AMTSurf(yield,['Average regional ' tmps ' yield (tonnes/ha)'],...
%         ['outfiles/yield/' list{i} '_yield.png']);
%     area=area.*(area<1e20);
%     amax=percentile(area,98);
%     area=area*100/percentile(area,98);
%     area(area>percentile(area,98))=percentile(area,98);
%     yield=yield.*(yield<1e20);
%     ymax=percentile(yield,98);
%     yield=yield*100/percentile(yield,98);
%     yield(yield>percentile(yield,98))=percentile(yield,98);
%     mkdir('outfiles/area',[list{i} '_overlay']);
%     mkdir(['outfiles/area/' list{i} '_overlay'],'file');
%     imwrite(ind2rgb(round(rot90(fliplr(area))),summer(100)),...
%         ['outfiles/area/' list{i} '_overlay/file/overlay.png'],'Alpha',rot90(fliplr(yield))/125+.2*(rot90(fliplr(area))>0));
%     mkdir('outfiles/yield',[list{i} '_overlay']);
%     mkdir(['outfiles/yield/' list{i} '_overlay'],'file');
%     imwrite(ind2rgb(round(rot90(fliplr(yield))),autumn(100)),...
%         ['outfiles/yield/' list{i} '_overlay/file/overlay.png'],'Alpha',rot90(fliplr(area))/125+.2*(rot90(fliplr(yield))>0));
%     makeLegend(summer(100),list{i},0,0.0,amax,0.0,ymax);
%     makeLegend(autumn(100),list{i},1,0.0,ymax,0.0,amax);
    fid=fopen(['outfiles/area/' list{i} '_overlay/doc.kml'],'w');
    fprintf(fid,['<?xml version="1.0" encoding="UTF-8"?>\n'...
        '<kml xmlns="http://www.opengis.net/kml/2.2">\n'...
        '<Folder>\n'...
        ['<name>Area: ' tmps '</name>\n']...
        ['<description>Global ' tmps ' area data</description>\n']...
        '<GroundOverlay>\n'...
        '<name>Large-scale overlay on terrain</name>\n'...
        '<description>Overlay shows amount of land used for ' tmps ' cultivation. Transparency corresponds to yield.\n'...
        '</description>\n'...
        '<Icon>\n'...
        '<href>file/overlay.png</href>\n'...
        '</Icon>\n'...
        '<LatLonBox>\n'...
        '<north>90.0</north>\n'...
        '<south>-90.0</south>\n'...
        '<east>-180.0</east>\n'...
        '<west>180.0</west>\n'...
        '</LatLonBox>\n'...
        '</GroundOverlay>\n'...
        '<ScreenOverlay>\n'...
        '<name>Legend</name>\n'...
        '<Icon>\n'...
        '<href>file/legend.png</href>\n'...
        '</Icon>\n'...
        '<overlayXY x="0" y="1" xunits="fraction" yunits="fraction"/>\n'...
        '<screenXY x="0" y="1" xunits="fraction" yunits="fraction"/>\n'...
        '<rotationXY x="0" y="0" xunits="fraction" yunits="fraction"/>\n'...
        '<size x="210" y="120" xunits="pixels" yunits="pixels"/>\n'...
        '</ScreenOverlay>\n'...
        '<ScreenOverlay>\n'...
        '<name>GLI</name>\n'...
        '<Icon>\n'...
        '<href>file/logo.png</href>\n'...
        '</Icon>\n'...
        '<overlayXY x="0" y="0" xunits="fraction" yunits="fraction"/>\n'...
        '<screenXY x="0" y="0" xunits="fraction" yunits="fraction"/>\n'...
        '<rotationXY x="0" y="0" xunits="fraction" yunits="fraction"/>\n'...
        '<size x="0" y="0" xunits="fraction" yunits="fraction"/>\n'...
        '</ScreenOverlay>\n'...
        '</Folder>\n'...
        '</kml>\n']);
    zip(['outfiles/area/' list{i} '_area.zip'],...
        {'doc.kml','file/overlay.png','file/legend.png','file/logo.png'},...
        ['outfiles/area/' list{i} '_overlay']);
    movefile(['outfiles/area/' list{i} '_area.zip'],...
        ['outfiles/area/' list{i} '_area.kmz']);
    fid=fopen(['outfiles/yield/' list{i} '_overlay/doc.kml'],'w');
    fprintf(fid,['<?xml version="1.0" encoding="UTF-8"?>\n'...
        '<kml xmlns="http://www.opengis.net/kml/2.2">\n'...
        '<Folder>\n'...
        ['<name>Yield: ' tmps '</name>\n']...
        ['<description>Global ' tmps ' yield data</description>\n']...
        '<GroundOverlay>\n'...
        '<name>Large-scale overlay on terrain</name>\n'...
        '<description>Overlay shows ' tmps ' yield. Transparency corresponds to amount of land used for its cultivation.\n'...
        '</description>\n'...
        '<Icon>\n'...
        '<href>file/overlay.png</href>\n'...
        '</Icon>\n'...
        '<LatLonBox>\n'...
        '<north>90.0</north>\n'...
        '<south>-90.0</south>\n'...
        '<east>-180.0</east>\n'...
        '<west>180.0</west>\n'...
        '</LatLonBox>\n'...
        '</GroundOverlay>\n'...
        '<ScreenOverlay>\n'...
        '<name>Legend</name>\n'...
        '<Icon>\n'...
        '<href>file/legend.png</href>\n'...
        '</Icon>\n'...
        '<overlayXY x="0" y="1" xunits="fraction" yunits="fraction"/>\n'...
        '<screenXY x="0" y="1" xunits="fraction" yunits="fraction"/>\n'...
        '<rotationXY x="0" y="0" xunits="fraction" yunits="fraction"/>\n'...
        '<size x="210" y="120" xunits="pixels" yunits="pixels"/>\n'...
        '</ScreenOverlay>\n'...
        '<ScreenOverlay>\n'...
        '<name>GLI</name>\n'...
        '<Icon>\n'...
        '<href>file/logo.png</href>\n'...
        '</Icon>\n'...
        '<overlayXY x="0" y="0" xunits="fraction" yunits="fraction"/>\n'...
        '<screenXY x="0" y="0" xunits="fraction" yunits="fraction"/>\n'...
        '<rotationXY x="0" y="0" xunits="fraction" yunits="fraction"/>\n'...
        '<size x="0" y="0" xunits="fraction" yunits="fraction"/>\n'...
        '</ScreenOverlay>\n'...
        '</Folder>\n'...
        '</kml>\n']);
    zip(['outfiles/yield/' list{i} '_yield.zip'],...
        {'doc.kml','file/overlay.png','file/legend.png','file/logo.png'},...
        ['outfiles/yield/' list{i} '_overlay']);
    movefile(['outfiles/yield/' list{i} '_yield.zip'],...
        ['outfiles/yield/' list{i} '_yield.kmz']);
    fclose('all');
    close all hidden
end